server:
  port: 80
  servlet:
    context-path: /
spring:
  resources:
    cache:
      cachecontrol:
        max-age: 30
  thymeleaf:
    mode: HTML5
haha:
  app:
    welcome: "Welcome to my system"
    person:
      names:
        - "yangzg"
        - 'yzg'
      address: Beijing, Chaoyang, ${user.dir}
logging:
  level:
    com.yangzg: debug
  file:
    path: ${user.dir}/logs