server:
  port: 80
  context-path: /
spring:
  resources:
    cache-period: 0
haha:
  app:
    welcome: "Welcome to my system"
    person:
      names:
        - "yangzg"
        - 'yzg'
      address: Beijing, Chaoyang